export const TEMP_STATIONS = {
  CW: ['HKP'],
  EST: ['SKW'],
  ILD: ['CCH', 'HKA'],
  KLC: ['KLC', 'SE1'],
  KC: ['TY1'],
  KT: ['KTG'],
  NTH: ['TKL'],
  SK: ['SKG', 'JKB'],
  ST: ['SHA'],
  SSP: ['SSP'],
  STH: ['HKS', 'STY'],
  TP: ['YCT', 'PLC'],
  TW: ['TWN', 'TW'],
  TM: ['TU1'],
  WC: ['HPV'],
  WTS: ['WTS'],
  YTM: ['KP', 'HKO'],
  YL: ['LFS', 'SK', 'YLP']
} as const
